# Generated by Django 3.2.7 on 2021-09-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
