# Generated by Django 3.2.7 on 2021-09-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
