# Generated by Django 3.2.7 on 2021-09-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowercare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hundredroseflowers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weddingbouquetflowers',
            name='user',
        ),
        migrations.DeleteModel(
            name='BasketBouquetFlowers',
        ),
        migrations.DeleteModel(
            name='HundredRoseFlowers',
        ),
        migrations.DeleteModel(
            name='WeddingBouquetFlowers',
        ),
    ]
