# Generated by Django 3.2.5 on 2021-08-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='card',
        ),
        migrations.RemoveField(
            model_name='flowerinpot',
            name='card',
        ),
    ]
