# Generated by Django 3.2.5 on 2021-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_flowerinpot_greeting_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerinpot',
            name='greeting_card',
            field=models.BooleanField(default=True, verbose_name='Наличие поздравителной карты'),
        ),
    ]
