# Generated by Django 3.2.7 on 2021-09-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20210923_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
